name: Load test
on: [workflow_dispatch]

# 1. You can remove the 'permissions' block if you aren't using OIDC anymore
# permissions:
#   id-token: write 

env:
  RESOURCE_GROUP: az2006-rg
  LOAD_TEST_RESOURCE: az2006loadtest
  AZURE_WEBAPP_NAME: az2006app84731

jobs:
  loadtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 2. Updated Login Step
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Run the load test (Keep this as is)
      - name: Azure Load Testing
        uses: azure/load-testing@v1.1.27
        with:
          loadTestConfigFile: 'config.yaml'
          loadTestResource: ${{ env.LOAD_TEST_RESOURCE}}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          env: |
            [
              {
              "name": "webapp",
              "value": "${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
              }
            ]
